# Generated by Django 2.2.10 on 2020-07-06 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 2, 59, 4, 387674, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
